# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syVT9xS6FUfLiD4fX18fSOKvjCgmxFbY
"""

money = 2000
if money >= 3000:
  print("Take Taxi")
else:
  print("Take Bus")

sum_var = 0
for i in range(10):
  sum_var += i
print(sum_var)

if(not sum_var):
  print(sum_var)

card = True
if money >= 3000 or card:
  print("Take Taxi")
else:
  pass

list_var = [1, 2, 3, 4, 5]
if 8 in list_var:
  print("8 is in the list")
else:
  print("Can't find input number")

#if statement 한 줄로 표현
if money >= 3000: print("Take Taxi")
else: print("Take Bus")

#조건부 표현식
score = 20
if score >= 60: message="Success"
else: message="Failure"
print(message)

message = "Success" if score >= 60 else "Failure"
print(message)